const mongoose = require("mongoose");

const EligibilitySchema = new mongoose.Schema({
  Id: { type: String, required: true },
  Name: { type: String, required: true },
  RecordTypeId: { type: String, required: true },
  Citizenship_Country__c: { type: String, required: true },
  Duo_12th_Gre_Percentile__c: { type: String, default: null },
  Duo_Comprehension__c: { type: String, default: null },
  Duo_Conversation__c: { type: String, default: null },
  Duo_Literacy__c: { type: String, default: null },
  Duo_Overall__c: { type: Number, default: null },
  Duo_Production__c: { type: String, default: null },
  Education_Country__c: { type: String, default: null },
  Exam_Type__c: { type: String, default: null },
  GMAT_Exam_Date__c: { type: String, default: null },
  GRE_Exam_Date__c: { type: String, default: null },
  Gmat_Integrated_Listening_Percentile__c: { type: Number, default: null },
  Gmat_Integrated_Listening_Score__c: { type: Number, default: null },
  Gmat_Quantitative_Percent__c: { type: Number, default: null },
  Gmat_Quantitative_Score__c: { type: Number, default: null },
  Gmat_Total_Percentile__c: { type: Number, default: null },
  Gmat_Verbal_Percentile__c: { type: Number, default: null },
  Gmat_Verbal_Score__c: { type: Number, default: null },
  Gre_Analytical_reasoning_Percentile__c: { type: Number, default: null },
  Gre_Analytical_reasoning_Score__c: { type: Number, default: null },
  Gre_Quantitative_reasoning_Score__c: { type: Number, default: null },
  Gre_Verbal_Reasoning_Percentile__c: { type: Number, default: null },
  Gre_Verbal_Reasoning_Score__c: { type: Number, default: null },
  Have_GMAT_Exam_Score__c: { type: Boolean, default: false },
  Have_GRE_Exam_Score__c: { type: Boolean, default: false },
  Programme__c: { type: String, required: true },
  Pte_Gmat_12th_Total_Marks_of_English__c: { type: Number, default: null },
  Pte_Listening__c: { type: Number, default: null },
  Pte_Reading__c: { type: Number, default: null },
  Pte_Speaking__c: { type: Number, default: null },
  Pte_Writing__c: { type: Number, default: null },
  School__c: { type: String, required: true },
  Total_Rank__c: { type: String, default: null },
  Verbal_Percent__c: { type: Number, default: null },
  Writing_Percent__c: { type: Number, default: null },
  Writing_Score__c: { type: Number, default: null },
});
let Eligibility = mongoose.model("Eligibility", EligibilitySchema);

module.exports = Eligibility;
